Repository googleapis/gax-java, pull requests merged in 2019-02, with the labels that each got.

#654 One more test for JSON serialization with field mask
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/ApiMessageHttpRequestTest.java
Labels: cla: yes

#650 Use ManagedChannelBuilder so user creds don't get overwritten
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: cla: yes, release blocking

#636 Opencensus Tracing: Start tracing bidi streaming callables.
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallableFactory.java
  gax/src/main/java/com/google/api/gax/tracing/TracedBidiCallable.java
  gax/src/main/java/com/google/api/gax/tracing/TracedResponseObserver.java
  gax/src/test/java/com/google/api/gax/tracing/TracedBidiCallableTest.java
Labels: cla: yes

#653 Opencensus Tracing: Start tracing BatchingCallables
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallableFactory.java
  gax/src/main/java/com/google/api/gax/tracing/ApiTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/NoopApiTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/TracedBatchingCallable.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerFactoryTest.java
  gax/src/test/java/com/google/api/gax/tracing/TracedBatchingCallableTest.java
Labels: cla: yes

#655 Release gax-java v1.38.0
  README.md
  benchmark/build.gradle
  build.gradle
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#659 Bump next snapshot
  benchmark/build.gradle
  build.gradle
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#652 Opencensus Tracing: Propagate the current tracer to grpc
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcClientCalls.java
Labels: cla: yes

#658 Opencensus Tracing: Add ability to pass static attributes to OpencensusTracerFactory
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/SpanName.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerFactoryTest.java
Labels: cla: yes

#656 Opencensus Tracing: fix nested traces + ApiTracer types
  gax/src/main/java/com/google/api/gax/tracing/ApiTracer.java
  gax/src/main/java/com/google/api/gax/tracing/ApiTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/NoopApiTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracer.java
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracerFactory.java
  gax/src/main/java/com/google/api/gax/tracing/TracedBatchingCallable.java
  gax/src/main/java/com/google/api/gax/tracing/TracedBidiCallable.java
  gax/src/main/java/com/google/api/gax/tracing/TracedServerStreamingCallable.java
  gax/src/main/java/com/google/api/gax/tracing/TracedUnaryCallable.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerFactoryTest.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerTest.java
  gax/src/test/java/com/google/api/gax/tracing/TracedBatchingCallableTest.java
  gax/src/test/java/com/google/api/gax/tracing/TracedBidiCallableTest.java
  gax/src/test/java/com/google/api/gax/tracing/TracedServerStreamingCallableTest.java
  gax/src/test/java/com/google/api/gax/tracing/TracedUnaryCallableTest.java
Labels: :rotating_light:, cla: yes

#657 Opencensus Tracing: Remove attempt started annotation
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracer.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerTest.java
Labels: :rotating_light:, cla: yes

#663 Update grpc to 1.18.0
  build.gradle
Labels: cla: yes, kokoro:force-run

#666 Update common protos version to 1.14.0
  build.gradle
Labels: cla: yes

#667 Release gax-java v1.39.0
  README.md
  benchmark/build.gradle
  build.gradle
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#668 Fix logic to remove retries from callable chains.
  gax/src/main/java/com/google/api/gax/rpc/Callables.java
Labels: cla: yes

#669 Opencensus Tracing: fix status attributes for server streaming attempt annotations
  gax/src/main/java/com/google/api/gax/retrying/ServerStreamingAttemptException.java
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracer.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerTest.java
Labels: cla: yes

#671 Bump to snapshot version for development
  benchmark/build.gradle
  build.gradle
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#670 Opencensus Tracing: trace server streaming.{first,all} as unary rpcs
  gax/src/main/java/com/google/api/gax/rpc/ServerStreamingCallable.java
  gax/src/main/java/com/google/api/gax/tracing/TracedServerStreamingCallable.java
  gax/src/test/java/com/google/api/gax/rpc/ServerStreamingCallableTest.java
Labels: cla: yes

#665 Opencensus Tracing: Add attributes for connection uuid
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcChannelUUIDInterceptor.java
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax/src/main/java/com/google/api/gax/tracing/ApiTracer.java
  gax/src/main/java/com/google/api/gax/tracing/NoopApiTracer.java
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracer.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerTest.java
Labels: :rotating_light:, cla: yes

#637 Opencensus Tracing: Start tracing client streaming callables.
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallableFactory.java
  gax/src/main/java/com/google/api/gax/tracing/TracedClientStreamingCallable.java
  gax/src/test/java/com/google/api/gax/tracing/TracedClientStreamingCallableTest.java
Labels: :rotating_light:, cla: yes

#674 Release gax-java v1.40.0
  README.md
  benchmark/build.gradle
  build.gradle
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#675 Auto-update the gax version in README.md
  README.md
Labels: cla: yes

#676 Bump next snapshot
  benchmark/build.gradle
  build.gradle
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#672 1.39.0 for all build tools
  README.md
Labels: cla: yes

#679 Add 200 as a valid HTTP status code
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonStatusCode.java
Labels: cla: yes

#678 Add an EmptyMessage class, analogous to protobuf's Empty
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/EmptyMessage.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/ApiMessageHttpRequestTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpRequestRunnableTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/MockHttpServiceTest.java
Labels: cla: yes

#677 1.40.0 for all build tools
  README.md
Labels: cla: yes

#682 Opencensus Tracing: minor tweaks
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracer.java
  gax/src/main/java/com/google/api/gax/tracing/TracedServerStreamingCallable.java
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerTest.java
Labels: cla: yes

#684 Expose LRO callables for HttpJson
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonCallableFactory.java
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonStubCallableFactory.java
Labels: cla: yes

#685 Add builder methods to EmptyMessage
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/EmptyMessage.java
Labels: cla: yes
