Repository googleapis/gax-java, pull requests merged in 2019-06, with the labels that each got.

#707 Use ComputeEngineChannelBuilder when directpath is enabled and default service account is used
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/testing/LocalChannelProvider.java
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProvider.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/InstantiatingHttpJsonChannelProviderTest.java
  gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax/src/main/java/com/google/api/gax/rpc/FixedTransportChannelProvider.java
  gax/src/main/java/com/google/api/gax/rpc/TransportChannelProvider.java
  gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
  gax/src/test/java/com/google/api/gax/rpc/FixedTransportChannelProviderTest.java
Labels: :rotating_light:, cla: yes

#731 Disable gRPC ServiceConfig look up
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: cla: yes

#580 Add Kokoro CI config
  .kokoro/build.sh
  .kokoro/common.cfg
  .kokoro/continuous/common.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/java11.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/presubmit/java8.cfg
  .kokoro/trampoline.sh
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: :rotating_light:, cla: yes

#729 Add netty epoll dependency, and set keepalive timeout for directpath
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Labels: :rotating_light:, cla: yes

#716 Batcher implementation with Synchronized `Batcher#flush`(without triggers)
  gax/src/main/java/com/google/api/gax/batching/v2/BatcherImpl.java
  gax/src/test/java/com/google/api/gax/batching/v2/BatcherImplTest.java
  gax/src/test/java/com/google/api/gax/rpc/testing/FakeBatchableApi.java
Labels: :rotating_light:, cla: yes

#733 Minor performance improvement to Distribution
  gax/src/main/java/com/google/api/gax/core/Distribution.java
Labels: :rotating_light:, cla: yes

#736 Release gax-java v1.46.0
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#737 Bump next snapshot
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#735 Add Kokoro release config
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.cfg
  .kokoro/release/drop.sh
  .kokoro/release/promote.cfg
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  build.gradle
  gax-bom/build.gradle
Labels: cla: yes

#739 Revert "Minor performance improvement to Distribution (#733)"
  gax/src/main/java/com/google/api/gax/core/Distribution.java
Labels: cla: yes

#740 Release gax-java v1.46.1
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#741 Upgrade dependency versions
  dependencies.properties
Labels: cla: yes

#742 Update google-http-java-client
  dependencies.properties
Labels: cla: yes

#734 Implementing ElementCount and ElementBytes Triggers
  gax/src/main/java/com/google/api/gax/batching/v2/BatcherImpl.java
  gax/src/main/java/com/google/api/gax/batching/v2/BatchingSettings.java
  gax/src/test/java/com/google/api/gax/batching/v2/BatcherImplTest.java
Labels: :rotating_light:, cla: yes

#745 Fix default timeout for non-retryable operations
  gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java
  gax/src/main/java/com/google/api/gax/rpc/Callables.java
Labels: cla: yes

#747 Release gax-java v1.47.0
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes
