Repository googleapis/gax-java, pull requests merged in 2019-07, with the labels that each got.

#751 oauth 0.16.2
  dependencies.properties
Labels: cla: yes

#750 Bump next snapshot
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: cla: yes

#752 Release gax-java v1.47.1
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#744 Introducing auto/timed flush for new Batcher.
  gax/src/main/java/com/google/api/gax/batching/v2/BatcherImpl.java
  gax/src/main/java/com/google/api/gax/batching/v2/BatchingSettings.java
  gax/src/test/java/com/google/api/gax/batching/v2/BatcherImplTest.java
Labels: cla: yes, needs work

#765 Small refactoring for v2.Batcher API
  gax/src/main/java/com/google/api/gax/batching/BlockingSemaphore.java
  gax/src/main/java/com/google/api/gax/batching/NonBlockingSemaphore.java
  gax/src/main/java/com/google/api/gax/batching/v2/BatcherImpl.java
  gax/src/main/java/com/google/api/gax/batching/v2/BatchingSettings.java
  gax/src/main/java/com/google/api/gax/rpc/ServerStreamingCallable.java
  gax/src/test/java/com/google/api/gax/batching/v2/BatcherImplTest.java
Labels: cla: yes
