Repository googleapis/gax-java, pull requests merged in 2019-09, with the labels that each got.

#748 Update RELEASING.md with autorelease/releasetool
  RELEASING.md
Labels: cla: yes

#784 Release gax-java v1.48.1
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#730 Update repository_rules.bzl
  repository_rules.bzl
Labels: cla: yes, type: bug

#786 Expose Batcher#sendOutstanding to provide async batch flushing
  gax/src/main/java/com/google/api/gax/batching/Batcher.java
  gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java
  gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: cla: yes

#787 Fix Race condition when shutting down executor/transport channel
  dependencies.properties
  gax-grpc/BUILD.bazel
  gax-httpjson/BUILD.bazel
  gax/BUILD.bazel
  gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Labels: cla: yes

#791 Update to Guava 28.1
  dependencies.properties
Labels: cla: yes

#788 Update opencensus, guava, and Truth
  dependencies.properties
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcCallableFactoryTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonCallableFactoryTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectCallableTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpRequestRunnableTest.java
Labels: cla: yes

#789 update google-auth-library to 0.17.2
  dependencies.properties
  gax/src/test/java/com/google/api/gax/tracing/OpencensusTracerFactoryTest.java
Labels: cla: yes

#794 make opencensus consistent
  dependencies.properties
Labels: cla: yes

#796 Release gax-java v1.49.0
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes
