Repository googleapis/gax-java, pull requests merged in 2020-09, with the labels that each got.

#1179 fix: [gax-java] add Vim files to .gitignore
  .gitignore
Labels: cla: yes

#1180 fix: [gax-java] Fix broken Bazel build
  dependencies.properties
  gax-grpc/BUILD.bazel
  gax-httpjson/BUILD.bazel
  gax/BUILD.bazel
  repositories.bzl
Labels: cla: yes

#1181 fix: [gax-java] Add speedy Bazel builds to Travis
  .travis.yml
Labels: cla: yes

#1183 chore: add CODEOWNERS and repo settings config
  .github/CODEOWNERS
  .github/sync-repo-settings.yaml
Labels: cla: yes

#1174 deps: update guava to 29.0-android
  dependencies.properties
Labels: cla: yes

#1190 feat: Allow user-agents to be specified by both internal headers and user headers
  gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Labels: cla: yes, kokoro:force-run, kokoro:run

#1193 chore: fix sync-repo-settings syntax
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#1191 fix: truncate RPC timeouts to time remaining in totalTimeout
  gax/src/main/java/com/google/api/gax/retrying/ExponentialRetryAlgorithm.java
  gax/src/test/java/com/google/api/gax/retrying/ExponentialRetryAlgorithmTest.java
  gax/src/test/java/com/google/api/gax/rpc/OperationCallableImplTest.java
Labels: cla: yes, kokoro:force-run

#1194 fix: update owners file with actools-java [gax-java]
  .github/CODEOWNERS
Labels: cla: yes
