Repository googleapis/gax-java, pull requests merged in 2020-02, with the labels that each got.

#871 fix: do not shut down executor when WatchDog is shut down
  gax/src/main/java/com/google/api/gax/rpc/Watchdog.java
  gax/src/test/java/com/google/api/gax/rpc/WatchdogTest.java
Labels: cla: yes

#878 fix: scale number of threads to scale with number of cpus
  gax/src/main/java/com/google/api/gax/core/InstantiatingExecutorProvider.java
Labels: cla: yes

#868 build: google format plugin upgrade
  build.gradle
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-grpc/src/main/java/com/google/longrunning/OperationsClient.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/RefreshingManagedChannelTest.java
  gax/src/main/java/com/google/api/gax/tracing/OpencensusTracer.java
Labels: cla: yes

#883 deps: update jacoco to 0.8.5
  build.gradle
Labels: cla: yes

#864 ci: setting up linkage monitor Kokoro build config for gax-java
  .kokoro/linkage-monitor.sh
  .kokoro/presubmit/linkage-monitor.cfg
Labels: cla: yes, kokoro:run

#882 dep: update protobuf and gRPC
  dependencies.properties
Labels: cla: yes

#885 gRPC 1.27.2
  dependencies.properties
Labels: cla: yes

#886 update http client
  dependencies.properties
Labels: cla: yes

#889 Release gax-java v1.54.0
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes
