Repository googleapis/gax-java, pull requests merged in 2020-04, with the labels that each got.

#993 feat: add ability to partially update retry settings
  gax-grpc/src/test/java/com/google/api/gax/grpc/SettingsTest.java
  gax/src/main/java/com/google/api/gax/rpc/ServerStreamingCallSettings.java
  gax/src/main/java/com/google/api/gax/rpc/UnaryCallSettings.java
  gax/src/test/java/com/google/api/gax/rpc/BatchingCallSettingsTest.java
  gax/src/test/java/com/google/api/gax/rpc/PagedCallSettingsTest.java
  gax/src/test/java/com/google/api/gax/rpc/ServerStreamingCallSettingsTest.java
  gax/src/test/java/com/google/api/gax/rpc/UnaryCallSettingsTest.java
Labels: cla: yes, kokoro:force-run

#992 deps: com.google.api:api-common
  dependencies.properties
Labels: cla: yes

#1013 deps: update grpc to 1.28.1
  dependencies.properties
Labels: cla: yes

#1014 Release gax-java v1.56.0
  README.md
  benchmark/build.gradle
  build.gradle
  dependencies.properties
  gax-bom/build.gradle
  gax-bom/pom.xml
  gax-grpc/build.gradle
  gax-httpjson/build.gradle
  gax/build.gradle
  samples/pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#858 test: cleaning up deprecated usages
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcCallContextTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectServerStreamingCallableTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamingCallableTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcTransportDescriptorTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/ProtoOperationTransformersTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/SettingsTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/ApiMessageOperationTransformersTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonCallContextTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/RetryingTest.java
  gax/src/test/java/com/google/api/gax/batching/ThresholdBatcherTest.java
  gax/src/test/java/com/google/api/gax/rpc/ApiExceptionsTest.java
  gax/src/test/java/com/google/api/gax/rpc/BatchedRequestIssuerTest.java
  gax/src/test/java/com/google/api/gax/rpc/CancellationTest.java
  gax/src/test/java/com/google/api/gax/rpc/FirstElementCallableTest.java
  gax/src/test/java/com/google/api/gax/rpc/RetryingTest.java
  gax/src/test/java/com/google/api/gax/rpc/SpoolingCallableTest.java
  gax/src/test/java/com/google/api/gax/rpc/UnaryCallableTest.java
Labels: cla: yes

#1017 chore: display call settings configuration through toString
  gax/src/main/java/com/google/api/gax/batching/BatchingCallSettings.java
  gax/src/main/java/com/google/api/gax/rpc/BatchingCallSettings.java
  gax/src/main/java/com/google/api/gax/rpc/ServerStreamingCallSettings.java
  gax/src/main/java/com/google/api/gax/rpc/UnaryCallSettings.java
  gax/src/test/java/com/google/api/gax/batching/BatchingCallSettingsTest.java
  gax/src/test/java/com/google/api/gax/rpc/BatchingCallSettingsTest.java
  gax/src/test/java/com/google/api/gax/rpc/ServerStreamingCallSettingsTest.java
  gax/src/test/java/com/google/api/gax/rpc/UnaryCallSettingsTest.java
Labels: cla: yes
