Repository googleapis/gax-java, pull requests merged in 2021-11, with the labels that each got.

#1549 fix: call ResponseMetadataHanlder#onTrailers before calling onClose
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcMetadataHandlerInterceptor.java
Labels: cla: yes

#1553 chore: upgrade Gradle to v7.3
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: cla: yes, automerge

#1554 chore: remove warnings and clean up codebase
  benchmark/src/jmh/java/com/google/api/gax/grpc/ServerStreamingCallableBenchmark.java
  build.gradle
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallContext.java
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcCallSettings.java
  gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcMetadataHandlerInterceptor.java
  gax-grpc/src/main/java/com/google/longrunning/OperationsSettings.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/CallOptionsUtilTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcCallableFactoryTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcClientCallsTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectServerStreamingCallableTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamingCallableTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcResponseMetadataTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcTransportDescriptorTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/RefreshingManagedChannelTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/SafeShutdownManagedChannelTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/SettingsTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java
  gax-grpc/src/test/java/com/google/longrunning/OperationsClientTest.java
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpRequestRunnable.java
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/longrunning/stub/HttpJsonOperationsStub.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/ApiMessageOperationTransformersTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonCallableFactoryTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/MockHttpServiceTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/longrunning/OperationsClientTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/testing/MockHttpService.java
  gax/src/main/java/com/google/api/gax/rpc/internal/ApiCallContextOptions.java
  gax/src/test/java/com/google/api/gax/rpc/OperationCallableImplTest.java
Labels: cla: yes

#1556 fix: pass error message when creating ApiException
  gax-grpc/src/test/java/com/google/api/gax/grpc/ProtoOperationTransformersTest.java
  gax-httpjson/src/test/java/com/google/api/gax/httpjson/ProtoOperationTransformersTest.java
  gax/src/main/java/com/google/api/gax/rpc/ApiExceptionFactory.java
Labels: cla: yes

#1555 fix: fix gRPC code conversion
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonExceptionCallable.java
  gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonStatusCode.java
Labels: cla: yes

#1565 chore: remove gh-pages docs publication code
  .gitignore
  build.gradle
  templates/apidocs_index.html.template
Labels: cla: yes

#1563 chore: remove benchmark module
  benchmark/README.md
  benchmark/build.gradle
  benchmark/src/jmh/java/com/google/api/gax/grpc/CallableBenchmark.java
  benchmark/src/jmh/java/com/google/api/gax/grpc/FakeBigtableService.java
  benchmark/src/jmh/java/com/google/api/gax/grpc/ServerStreamingCallableBenchmark.java
  build.gradle
  settings.gradle
  versions.txt
Labels: cla: yes

#1564 chore: remove samples directory that is no longer used
  samples/README.rst
  samples/pom.xml
Labels: cla: yes, samples

#1571 deps: upgrade protobuf to 3.19.1
  .github/workflows/ci.yaml
  WORKSPACE
  dependencies.properties
Labels: cla: yes

#1559 deps: update grpc to 1.42.1
  .github/workflows/ci.yaml
  dependencies.properties
Labels: cla: yes, automerge

#1573 chore: minor cleanups
  WORKSPACE
Labels: cla: yes
