Repository googleapis/gax-java, pull requests merged in 2021-04, with the labels that each got.

#1336 docs: cloud rad java doc generation
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  build.gradle
Labels: cla: yes, kokoro:force-run

#1328 feat: wrap non-retryable RPCs in retry machinery
  gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java
  gax/src/main/java/com/google/api/gax/rpc/Callables.java
  gax/src/test/java/com/google/api/gax/rpc/CallableTest.java
  gax/src/test/java/com/google/api/gax/tracing/TracedCallableTest.java
Labels: cla: yes

#1332 feat: dynamic flow control p3: add FlowControllerEventStats
  gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java
  gax/src/main/java/com/google/api/gax/batching/FlowControlEventStats.java
  gax/src/main/java/com/google/api/gax/batching/FlowController.java
  gax/src/test/java/com/google/api/gax/batching/FlowControlEventStatsTest.java
  gax/src/test/java/com/google/api/gax/batching/FlowControllerTest.java
Labels: automerge, cla: yes, kokoro:force-run

#1344 fix: fix watchdog NPE red herring
  gax/src/main/java/com/google/api/gax/rpc/Watchdog.java
  gax/src/test/java/com/google/api/gax/rpc/WatchdogTest.java
Labels: cla: yes, kokoro:force-run

#1347 fix: fix dynamic flow control setting checks
  gax/src/main/java/com/google/api/gax/batching/DynamicFlowControlSettings.java
  gax/src/test/java/com/google/api/gax/batching/DynamicFlowControlSettingsTest.java
Labels: cla: yes

#1354 deps: remove codecov.io
  .github/workflows/ci.yaml
  .kokoro/build.sh
  README.md
  codecov.yml
Labels: cla: yes
