Repository googleapis/gax-java, pull requests merged in 2022-06, with the labels that each got.

#1562 chore: Add Maven build
  .github/workflows/ci.yaml
  .gitignore
  .kokoro/maven-build.sh
  gax-bom/pom.xml
  gax-grpc/pom.xml
  gax-httpjson/pom.xml
  gax/build.gradle
  gax/pom.xml
  gax/src/main/resources/dependencies.properties
  java.header
  license-checks.xml
  pom.xml
Labels: cla: yes

#1713 deps: update dependency com.google.api.grpc:proto-google-common-protos to v2.9.0
  .kokoro/downstream-client-library-check.sh
  build.gradle
  dependencies.properties
Labels: automerge, downstream-check:run

#1715 ci: maven options to suppress unnecessary outputs
  .kokoro/maven-build.sh
Labels: automerge
