Repository googleapis/gax-java, pull requests merged in 2022-01, with the labels that each got.

#1587 deps: update dependency com.google.api.grpc:proto-google-common-protos to v2.7.1
  dependencies.properties
Labels: automerge

#1590 deps: update dependency com.google.api:api-common to 2.1.2
  dependencies.properties
Labels: automerge

#1568 chore: refactor channel pool
  gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java
  gax-grpc/src/main/java/com/google/api/gax/grpc/RefreshingManagedChannel.java
  gax-grpc/src/main/java/com/google/api/gax/grpc/SafeShutdownManagedChannel.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcClientCallsTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/RefreshingManagedChannelTest.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/SafeShutdownManagedChannelTest.java
Labels: cla: yes, automerge

#1589 test: fix flaky BatcherImplTest.testThrottlingNonBlocking() test
  gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: automerge

#1595 chore(deps): upgrade gRPC
  dependencies.properties
Labels: automerge

#1488 feat: pass a CallCredentials to grpc-java for DirectPath
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Labels: cla: yes

#1600 test: further deflake testThrottlingBlocking()
  gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Labels: automerge

#1603 chore: update cloud rad doclet
  build.gradle
Labels: automerge

#1436 feat: add api key support
  gax/src/main/java/com/google/api/gax/rpc/ClientContext.java
  gax/src/main/java/com/google/api/gax/rpc/StubSettings.java
  gax/src/main/java/com/google/api/gax/rpc/internal/EnvironmentProvider.java
  gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Labels: cla: yes

#1606 chore: migrate to use common EnvironmentProvider interface
  gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
  gax/src/main/java/com/google/api/gax/rpc/mtls/MtlsProvider.java
  gax/src/test/java/com/google/api/gax/rpc/mtls/MtlsProviderTest.java
Labels: automerge
